server:
  port: 8080

spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: Rishabh@28
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

address:
  service:
    url: http://localhost:8081/api/v1/addresses
